### ISSUE TITLE
bower endpoint doesn't work

### ISSUE THREAD

**Issue by ynosa** [matthewp/jspm-bower#6] opened 2015-01-21 13:19 UTC
bower endpoint doesn't work when running

`jspm install bower:jquery`

it throws:
`err  Error looking up bower:jquery
     TypeError: Object #<BowerLocation> has no method 'lookup'`

jspm-bower version installed from npm: jspm-bower@0.0.3
jspm version: jspm@0.10.6

**Comment by matthewp** [comment] 2015-02-19 14:42
Dupe of #5

**Closed as completed by matthewp** 2015-02-19 14:42 UTC
